<Project>
  <PropertyGroup>
    <DataAiSparkRuntimePackageRoot>$(MSBuildThisFileDirectory)..\</DataAiSparkRuntimePackageRoot>
    <DataAiSparkPackageJarsDirectory>$(DataAiSparkRuntimePackageRoot)tools\jars</DataAiSparkPackageJarsDirectory>
    <DataAiSparkPackageCliDirectory>$(DataAiSparkRuntimePackageRoot)tools\cli</DataAiSparkPackageCliDirectory>
  </PropertyGroup>
</Project>
